### ISSUE TITLE
Error: Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by pvandenabeele** [mtgoncurve/mtgoncurve.com#91]
Hello,
First of all, thanks for your tool!!
When entering a deck list that contains some card names, I get the below error message in console:

e15955f….module.wasm:0x6a78e Uncaught RuntimeError: memory access out of bounds
    at e15955f….module.wasm:0x6a78e
    at Module.w (1.landlord.worker.js:1:1700)
    at landlord.worker.js:1:3218

and in module.wasm
    local.get $var90
    local.get $var0
    i32.store offset=12 <=== here
    block $label678
      block $label1896 (result i32)

The error seems to be triggered by the below card (the rest of the whole deck list works)
1 Lim-Dûl's Vault (ALL) 107

Thank you

**Comment by DaComputerNerd717** [comment]
I found the same in #94 . Seems to be triggered by non-ASCII symbols in card names

Only workaround I could find was to use a different card with the same mana cost and mana-sourcing capability
